### ISSUE TITLE
Elbow radii 

### ISSUE THREAD

**Issue by thejase** [Aricwithana/LCARS-SDK#4]
Let me start by complimenting you on this breathtaking API.  LCARS was one of the reasons I stayed so passionate with software engineering--specifically UI and layout engineering.

So, I've been happily trying to understand and deconstruct your approach.  It's fabulous!  However, I did find one small, but significant detail that I commonly question with LCARS implementations: the Elbow.  From my research, the inner and outer radii share a commonality with the content of the inner pane, or the margin.  Specifically, this is what I have observed (taken from a screenshot of Star Trek: Nemesis):

![image](https://cloud.githubusercontent.com/assets/787276/19101887/88bf7342-8a80-11e6-9e37-f31e6faebf08.png)

Essentially, the radius of the outer border works harmoniously with the radius of the inner border.  I'm not sure in this instance what the inner border's formula is.

Now, if I take the same radii measurements from `/interfaces/color-generator/index.html`, I notice that the outer radius is only dependant on the largest side's main axis (in this case, the left width):

![image](https://cloud.githubusercontent.com/assets/787276/19101928/e0eba3b0-8a80-11e6-8d86-74e48ce6b5d5.png)

Take into account the relationship between the inner and outer radius:

![image](https://cloud.githubusercontent.com/assets/787276/19101995/6e757e0e-8a81-11e6-95c1-cfc6cc07e6c2.png)

The difference side by side:

![image](https://cloud.githubusercontent.com/assets/787276/19102067/2031aa3c-8a82-11e6-8249-21f243c353ac.png)

Luminance-overlayed:

![image](https://cloud.githubusercontent.com/assets/787276/19102151/aefa1dbc-8a82-11e6-9ff4-58cb15a7dc75.png)

All in all, I know it might seem a bit nit-picky, but I've always been fascinated by the subtleties that Okuda used to convey relationships between sets of data.  I just thought I would throw this in here for discussion.

For what it's worth, this is a great article about shared border radii... a quick and lovely read: http://joshnh.com/weblog/getting-inner-border-radius-just-right/

**Comment by thejase** [comment]
And adding one more example (a screencap of a PADD being held):
![image](https://cloud.githubusercontent.com/assets/787276/19103960/de67a298-8a8e-11e6-8e3b-68115c29a630.png)

Perspective adjusted + 400% zoom:
![image](https://cloud.githubusercontent.com/assets/787276/19104001/10fab79a-8a8f-11e6-8fb8-cd16b8ae1bad.png)

Radii outlines:
![image](https://cloud.githubusercontent.com/assets/787276/19104085/65f950ee-8a8f-11e6-8a97-d19bf0668c6f.png)

**Comment by thejase** [comment]
One more example, using your large-panel example.  Original on left purple, modified on right purple:
![image](https://cloud.githubusercontent.com/assets/787276/19105190/9794e626-8a95-11e6-8400-1eeee40e1fd8.png)

Notice that the right's top elbow outer radius is enlarged, but the bottom one is shrunk.  This is because the top's largest axis is the **top bar**, and the bottom's largest axis is the **side bar**:
![image](https://cloud.githubusercontent.com/assets/787276/19105474/f2b3d6e2-8a96-11e6-8183-d5e34fa23bce.png)

**Comment by Aricwithana** [comment]
Well I can't say your wrong and I can't say I've not tried to remedy it.  I ran into a couple walls though.

First being that the CSS border radius doesn't work the way we'd like it to to create the offset elbow radius.  Border radius is directly tied to the height/width of the element itself so the radius will change depending on the size of the elbow for the outer radius is not static since they can change height/width for responsive movement.  Inner radius is static for it doesn't change sizes for it has no settings to base its size off in relation to the parent.

The other one being that, Mr. Okuda wasn't the only one designing LCARS and they were all doing it on a crunch time frame generally (especially for the tv versions).  There are a lot of sources to pull from and many times the conflict with each other.  I work with the rule of: 'if it is seen it can be done, even if it was a production error'.  This includes things like a mouse cursor and white text on buttons.

I have considered making a version of the SDK that uses SVG and applying a svg js library to help control things.

All in all, the SDK just provides a base standard to work with.  Since things are open, unlike all other LCARS projects, anyone can adjust anything so applying the techniques you want are entirely possible but they need to be custom placed/used.

**Comment by thejase** [comment]
Thanks for taking time to read these and consider.  I definitely agree that browser handling of border-radius is tricky, so I see the reasoning to stick with contextual metrics. 

I've been tempted to create a fork that includes a Sass representation of the CSS. I might play around and see if there is a way to incorporate this configuration as an "option" in a scalable way. 

Once again, I'm heavily impressed!!  Love your work!

**Comment by Aricwithana** [comment]
Thanks!  I love the LCARS methodology, just wish I knew a backend lang well enough to do some feature rich software.

No problem!  There are a few ways it can be done, just depends on the layout and what the elbow is being used for.  If the elbow is static and there is the right sizing for border radius, all should be good.  Could also play with adding an extra element inside the elbow to be the background and radius so that if the elbow does get smaller, the radius doesn't change.  Just means there is an absolute minimum width/height that specific elbow can be.

Let me know if you do with the Sass.  I played around with some React to possibly replace my js API but I didn't get too far with it because of life.

**Comment by thejase** [comment]
That's some great ideas to get started with!  

Yeah, I'm just going to focus on the Sass first, but I would be lying if I hadn't started mentally wrapping the API into an Ember app. I've already been thinking through how to animate panel changes/intros/outros by climbing up the DOM from each leaf -> nodes -> root. 

I'll create a fork as I play. If there's viability, I'll reference a PR.

**Comment by thejase** [comment]
By the way, do you have an example that generates that wide panel referenced above?  It's really complex, and thus a great testing ground.

**Comment by Aricwithana** [comment]
Yea Sass might be easier when working without the JS api or using a different setup to work with the DOM/CSS. 

Actually I've got a small testing setup for animations for showing/hiding a frame and content.  Sure I can share that specific UI with you for testing.  Hit me up on facebook there and we can swap skype!

**Comment by Aricwithana** [comment]
I'll play around with some things here tonight and see what I can pull up.  If I work with the idea that as long as the elbow is equal to or larger than the default min height/width (which seems to be about 75x75) then the inner radius will pull off the visual you're looking for I believe.

**Comment by Aricwithana** [comment]
![samples](https://cloud.githubusercontent.com/assets/2460319/19140159/f7b259de-8b4f-11e6-9c73-f0e1f89fde33.png)

Take a look at the image there and let me know if this is closer to what you are looking for for technique. Worked with things in the way that would be rendered in the webview.  Minimum height of the elbow would be 93px for the 'default' elbow.

**Comment by thejase** [comment]
^^ Forgive me, as I am not versed in arc length geometry, but it sounds to me that their linear in relation to radii?  If so, your calculations seem close, but I think it's more around 90px arc.  `([largest elbow width = 150px?] + [inner arc]) / 2`.  Does that work with the webviews you're seeing?  I did some devtool modifications in browser, and 90 is looking great for `border-radius` in this formula.

An example of a live edit of the color generator:

BEFORE (75px)
![image](https://cloud.githubusercontent.com/assets/787276/19143387/692eb046-8b58-11e6-9621-799e980172e8.png)

AFTER (with unneccesary calc() to show calculation):
![image](https://cloud.githubusercontent.com/assets/787276/19143311/ef37c8fe-8b57-11e6-8294-21086b42de00.png)
![image](https://cloud.githubusercontent.com/assets/787276/19143320/fea497ae-8b57-11e6-9d08-89975e44e212.png)

On a tangent (pun intended), isn't this starting to look like the Atari logo?!
![image](https://cloud.githubusercontent.com/assets/787276/19143452/e3a051ea-8b58-11e6-97d0-85d8991c7101.png)

**Comment by Aricwithana** [comment]
Here is a quick few trials I worked with along with a classic framing.

The classic framing is using the 35px inner arc variant which effectively makes the elbow have a min height of 93px, which in many cases will end up being 95px because of how LCARS spacing can flow.  Check out the 'guided' version to see how that works.

Thoughts?

 

![elbows](https://cloud.githubusercontent.com/assets/2460319/19217007/29b8fa1e-8d99-11e6-8375-d90b666e21d4.png)

![image](https://cloud.githubusercontent.com/assets/2460319/19217428/91672972-8da0-11e6-9723-c09f39d56c6f.png)

![image](https://cloud.githubusercontent.com/assets/2460319/19217443/bc91c300-8da0-11e6-8577-95ba3ea4c172.png)

**Comment by thejase** [comment]
Those are some "stellar" elbows!  I love how the midpoint of the arc is constant. 

This is perfection, and one of the primary reasons I fell in love with LCARS.

**Comment by Aricwithana** [comment]
Sweet!  Then we'll call these the default elbows done!  I'll take the equation and work on examples for other named sizes provided.

I was also thinking of along side the generic default names like large, small, etc...for elbow sizes I can also add some classes like 'arc-90-30' instead of a size name.  This way a whole slew of elbow arcs can be used for options.  This would mean then that the named sizes would just equal one of the 'arc-x-x' classes.

**Comment by thejase** [comment]
Lovely.  i like the specificity of arc-90-30. It helps against regression issues for updates.

**Comment by Aricwithana** [comment]
Below are samples of what I think will work for the other 'sizes'.  Essentially took the default overlapping circles and scaled them up and down basing things on the typical LCARS spacing and such.

Let me know if you like or have tweaks!  Small and Large I just used them in the most typical fashion we see.

![large-elbows](https://cloud.githubusercontent.com/assets/2460319/19407082/875a8abc-925c-11e6-8e3d-7c2f5715a20b.png)
![elbows](https://cloud.githubusercontent.com/assets/2460319/19407083/875ca7b6-925c-11e6-8551-bb12ddcc56a0.png)

**Comment by Aricwithana** [comment]
New Elbow settings are all in place!
