### ISSUE TITLE
$.createObject({})

### ISSUE THREAD

**Issue by sfranzyshen** [Aricwithana/LCARS-SDK#8]
Since $.createObject({}) has been eliminated how do we get things started? Do we use the LCARS.create() API on every element ... or does LCARS.create() now handle things like createObject() did?

From:
```
var exampleUI = {type:'wrapper', id:'wpr_viewport', version:'row', flex:'h', arrive:function(){$(this).viewport('zoom', {width:1920, height:1080});}, children:[
......
$(document).on('ready', function(){
	$(exampleUI).createObject({appendTo:'body'});
});
```
To:
```
var exampleUI = {type:'???', id:'wpr_viewport', version:'row', flex:'h', arrive:function(){$(this).viewport('zoom', {width:1920, height:1080});}, children:[
......
$(document).on('ready', function(){
        $('body').append( LCARS.create($(exampleUI)).dom );
});

```

**Comment by Aricwithana** [comment]
https://github.com/Aricwithana/LCARS-SDK/wiki/LCARS.create

Yep, LCARS.create replaces that jQuery wrapper.  It generates a New Object Constructor and returns a reference to the active element stored under LCARS.active

The object.dom is a jQuery reference so it does not need to be wrapped in a $(object.dom);  

I'll update the Wiki with this information since I think I missed to make that note about the DOM reference stored within the object instance.

<pre><code>

var ui = {type:'wrapper', id:'project-viewport', flex:'h'}

$(document).on('ready', function(){
        $('body').append( LCARS.create(ui).dom );
});
</code></pre>

**Comment by sfranzyshen** [comment]
wow! thank you for the quick response ... i've been following things and didn't think it would be released until tomorrow ... day 182 ... glad to see it up! i'm excited to get my hands dirty ;) can't wait to start porting things over ... thank you for your hard work ... it's appreciated!

**Comment by Aricwithana** [comment]
Oh yea that is my fault.  When i checked the number last night, it was after midnight so when I added +1 day, it is actually tomorrow.  Was hoping nobody would notice, haha.  Glad to help!

**Comment by sfranzyshen** [comment]
anyone following along  with this ... the jquery has been updated too! (v3.3.1) so it should be ...

```
var ui = {type:'wrapper', id:'project-viewport', flex:'h'}

$( document ).ready(function() {
        $('body').append( LCARS.create(ui).dom );
});

```
